### ISSUE TITLE
Ability to use custom template changes

### ISSUE THREAD

**Issue by cb3inco** [linuxserver/docker-bookstack#108]
-----------------------------

## Desired Behavior
Prior to 28.0.1 I was able to manually mount /var/www/html/themes in my docker-compose file to modify certain files to update the default template. I would like this ability in subsequent versions.

## Current Behavior
As of 28.0.2 and 28.0.3 it seems to be no longer possible to mount this path as a volume and make custom template changes.

## Alternatives Considered
Not sure other than compiling my own image.

**Comment by ssddanbrown** [comment]
Potentially related to https://github.com/linuxserver/docker-bookstack/issues/107#issuecomment-927134415

**Comment by Sazzels** [comment]
i have the same issue.
since i use bookstack mainly as a documentation platform, i change some spellings via the template mount into the container and setting the environment variable (docker-compose).

```yaml
environment:
      ...
      # Theme
      - APP_THEME='<name>'
      ...
volumes:
      ...
      - '/path/to/themes-data/de:/var/www/html/themes/<name>/lang/de'
      - '/path/to/themes-data/de_informal:/var/www/html/themes/<name>/lang/de_informal'
      ...
```

removing this - solves the "File not found!" issue.
