### ISSUE TITLE
Timezone Not Respected

### ISSUE THREAD

**Issue by serenewaffles** [linuxserver/docker-bookstack#115]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------
Revision time stamps are not localized. I'm not sure if this is a Bookstack bug or a container bug or perhaps intended behavior?
## Expected Behavior
Time stamps for revisions should be displayed in the container's timezone. e.g. `TZ=America/New_York` should result in seeing edit timestamps in Eastern Time,

## Current Behavior

Time stamps are displayed in UTC.
## Steps to Reproduce

1. Set up a Bookstack instance
2.
3.
4.

## Environment
**OS:** Ubuntu Server 20.04.3 LTS
**CPU architecture:** arm64
**How docker service was installed:** From the official docker repo (https://get.docker.com)

## Command used to create docker container (run/create/compose/screenshot)

```
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=500
      - PGID=100
      - APP_URL=https://XXX.net
      - DB_HOST=XXX
      - DB_USER=bookstack
      - DB_PASS=XXX
      - DB_DATABASE=bookstackapp
      - APP_THEME=test
      - TZ=America/New_York
    volumes:
      - bookstack:/config
#    ports:
#      - 6875:80
    restart: unless-stopped
    networks:
      - caddy
    labels:
      caddy: XXX.net
      caddy.reverse_proxy: "{{upstreams 80}}"
```
