### ISSUE TITLE
[BUG] bookstack_db Pulling no matching manifest for linux/arm/v8 in the manifest list entries

### ISSUE THREAD

**Issue by truthsword** [linuxserver/docker-bookstack#175]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

My docker stack is not working > No manifest found on pull (notification below)

```
version: "3"
services:
  bookstack:
    image: "lscr.io/linuxserver/bookstack:latest"
    container_name: bookstack
    environment:
      - PUID=1001
      - PGID=1001
      - APP_URL=http://192.168.1.100
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_PASS=bookstack
      - DB_DATABASE=bookstackapp
    volumes:
      - "/home/docker/bookstack/config:/config"
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - bookstack_db
  bookstack_db:
    image: "lscr.io/linuxserver/mariadb:latest"
    container_name: bookstack_db
    environment:
      - PUID=1001
      - PGID=1001
      - MYSQL_ROOT_PASSWORD=maria
      - TZ=America/New_York
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=bookstack
    volumes:
      - "/home/docker/bookstack/mariadb/config:/config"
    restart: unless-stopped
```
![](https://i.imgur.com/3L92tag.png}

Running on RPi.

Please advise.

### Expected Behavior

Normal pull

### Steps To Reproduce

Compose file above.

### Environment

```markdown
- OS:RPi
- How docker service was installed:RPi, fully updated today.
```

### CPU architecture

armhf

### Docker creation

```bash
See compose file above.
```

### Container logs

```bash
No container at this point, so no logs.
```
![](https://i.imgur.com/6v3AuMa.png)
