### ISSUE TITLE
[BUG] unable to take locks: No such file or directory

### ISSUE THREAD

**Issue by modem7** [linuxserver/docker-bookstack#181]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Container restarting on start.

```bash
[mod-init] Attempting to run Docker Modification Logic
s6-rc: fatal: unable to take locks: No such file or directory
s6-linux-init-shutdownd: warning: /run/s6/basedir/scripts/rc.shutdown exited 111
[mod-init] Attempting to run Docker Modification Logic
s6-rc: fatal: unable to take locks: No such file or directory
s6-linux-init-shutdownd: warning: /run/s6/basedir/scripts/rc.shutdown exited 111
[mod-init] Attempting to run Docker Modification Logic
s6-rc: fatal: unable to take locks: No such file or directory
s6-linux-init-shutdownd: warning: /run/s6/basedir/scripts/rc.shutdown exited 111
[mod-init] Attempting to run Docker Modification Logic
s6-rc: fatal: unable to take locks: No such file or directory
s6-linux-init-shutdownd: warning: /run/s6/basedir/scripts/rc.shutdown exited 111
[mod-init] Attempting to run Docker Modification Logic
s6-rc: fatal: unable to take locks: No such file or directory
s6-linux-init-shutdownd: warning: /run/s6/basedir/scripts/rc.shutdown exited 111
[mod-init] Attempting to run Docker Modification Logic
s6-rc: fatal: unable to take locks: No such file or directory
s6-linux-init-shutdownd: warning: /run/s6/basedir/scripts/rc.shutdown exited 111
[mod-init] Attempting to run Docker Modification Logic
s6-rc: fatal: unable to take locks: No such file or directory
s6-linux-init-shutdownd: warning: /run/s6/basedir/scripts/rc.shutdown exited 111
[mod-init] Attempting to run Docker Modification Logic
```

```yaml
# Bookstack - BookStack is a simple, self-hosted, easy-to-use platform for organising and storing information.
  bookstack:
    image: linuxserver/bookstack
    container_name: Bookstack
    hostname: Bookstack
    networks:
      pihole:
        ipv4_address: '172.22.0.119'
      isolated:
    ports:
      - "32231:80"
    depends_on:
      - bookstackdb
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - DB_HOST=bookstackdb
      - DB_USER=$BOOKSTACK_USER
      - DB_PASS=$BOOKSTACK_PASSWORD
      - DB_DATABASE=$BOOKSTACK_DATABASE
      - ALLOW_ROBOTS=true
      - APP_URL=https://www.$DOMAINNAME
      - APP_DEFAULT_DARK_MODE=true
      - APP_PROXIES=$BS_APP_PROXIES
      - APP_THEME=rss
      # - WKHTMLTOPDF=/usr/bin/wkhtmltopdf #issue https://github.com/BookStackApp/BookStack/issues/2490
      - MAIL_DRIVER=smtp
      - MAIL_FROM_NAME=$BS_MAIL_FROM_NAME
      - MAIL_FROM=$BS_MAIL_FROM
      - MAIL_HOST=$SMTP_HOST
      - MAIL_PORT=$SMTP_PORT
      - MAIL_USERNAME=$SMTP_USERNAME
      - MAIL_PASSWORD=$BS_MAIL_PASSWORD
      - MAIL_ENCRYPTION=$BS_MAIL_ENCRYPTION
      - GOOGLE_APP_ID=$BS_GOOGLE_APP_ID
      - GOOGLE_APP_SECRET=$BS_GOOGLE_APP_SECRET
      - GOOGLE_AUTO_CONFIRM_EMAIL=true
      - GOOGLE_AUTO_REGISTER=true
      - GITHUB_APP_ID=$BS_GITHUB_APP_ID
      - GITHUB_APP_SECRET=$BS_GITHUB_APP_SECRET
      - GITHUB_AUTO_CONFIRM_EMAIL=true
      - GITHUB_AUTO_REGISTER=true
      - SESSION_SECURE_COOKIE=true
      - LOG_FAILED_LOGIN_MESSAGE="Failed login for %u"
      - CACHE_DRIVER=database
      - SESSION_DRIVER=database
      - DOCKER_MODS=linuxserver/mods:swag-cloudflare-real-ip
    logging:
      driver: "local"
      options:
        max-size: 10m
        max-file: "3"
    labels:
      # - backup
      - autoheal=true
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.bookstack-rtr.entrypoints=https"
      - "traefik.http.routers.bookstack-rtr.rule=Host(`bookstack.$DOMAINNAME`) || Host(`omegawiki.$DOMAINNAME`) || Host(`www.$DOMAINNAME`) || Host(`$DOMAINNAME`)"
      # - "traefik.http.routers.bookstack-rtr.tls=true"
      ## Middlewares
      # - "traefik.http.routers.bookstack-rtr.middlewares=chain-authelia@file"
      - "traefik.http.routers.bookstack-rtr.middlewares=chain-no-auth@file"
      # Redirect non-www to www middleware
      - "traefik.http.middlewares.bookstack-redirect.redirectregex.regex=^https?://$DOMAINNAME/(.*)"
      - "traefik.http.middlewares.bookstack-redirect.redirectregex.replacement=https://www.$DOMAINNAME/$${1}"
      - "traefik.http.middlewares.bookstack-redirect.redirectregex.permanent=true"
      ## HTTP Services
      - "traefik.http.routers.bookstack-rtr.service=bookstack-svc"
      - "traefik.http.services.bookstack-svc.loadbalancer.server.port=80"
      ## Homepage
      - homepage.name=Bookstack
      - homepage.group=Other
      - homepage.icon=https://raw.githubusercontent.com/modem7/MiscAssets/master/Icons/HeimdallIcons/bookstack.png
      - homepage.href=https://$DOMAINNAME
    volumes:
      - $USERDIR/Bookstack/:/config
    healthcheck:
      test: curl -fSs 127.0.0.1:80/status || exit 1
      start_period: 60s
      interval: 5s
      timeout: 10s
      retries: 3
    restart: always
```

### Expected Behavior

For container to start

### Steps To Reproduce

Starting container with above config.

### Environment

```markdown
- OS: Ubuntu 22.04
- How docker service was installed: APT via Docker instructions.
```

### CPU architecture

x86-64

### Docker creation

```bash
docker compose up
```

### Container logs

```bash
See above
```

### Additional Information

23.06.1 works as expected.
