### ISSUE TITLE
[BUG] Environment variables not being passed to /config/www/.env

### ISSUE THREAD

**Issue by XStylus** [linuxserver/docker-bookstack#189]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The following docker-compose environment variables are not being passed to the Bookstack .env file at /config/www/.env:

      - MAIL_DRIVER=
      - MAIL_HOST=
      - MAIL_PORT=
      - MAIL_USERNAME=
      - MAIL_PASSWORD=
      - MAIL_ENCRYPTION=
      - MAIL_FROM_NAME=
      - MAIL_FROM=
      - GOOGLE_AP_ID=
      - GOOGLE_APP_SECRET=
      - GOOGLE_AUTO_REGISTER=

### Expected Behavior

When the above variables are entered into "environment:" on docker-compose, it is expected that they be passed along to /config/www/.env.

There is an undesirable workaround by way of using a separate .env file alongside the docker-compose file, or by manually editing the /config/www/.env file after installation.

### Steps To Reproduce

1. Add the affected variables to docker compose.
2. Install Bookstack using docker compose file.
3. View /config/www/.env file.
4. See that the affected variables remain at their defaults and not as specified in the docker compose file.

### Environment

```markdown
- OS: ubuntu 22.04.3 LTS
- How docker service was installed: Distro packagemanager
```

### CPU architecture

x86-64

### Docker creation

```bash
# Docker Compose file for Bookstack

version: "2"
services:
  bookstack:
    image: linuxserver/bookstack:latest
    container_name: bookstack_app
    restart: unless-stopped
    depends_on:
      - bookstack_db
    volumes:
      - /mnt/Secondary/docker/bookstack/config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=https://wiki.example.com
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_PASS=SuperPWGoesHere
      - DB_DATABASE=bookstackapp
      - DB_PORT=3306
# Email configuration settings
      - MAIL_DRIVER=smtp
      - MAIL_HOST=smtp.mailserver.com
      - MAIL_PORT=587
      - MAIL_USERNAME=example@example.com
      - MAIL_PASSWORD=SuperPWGoesHere
      - MAIL_ENCRYPTION=tls
      - MAIL_FROM_NAME="BookStack Wiki"
      - MAIL_FROM=noreply@example.com
      - GOOGLE_AP_ID=GoogleAppIDGoesHere.apps.googleusercontent.com
      - GOOGLE_APP_SECRET=GoogleAppSecretGoesHere
      - GOOGLE_AUTO_REGISTER=true
#    ports:
#      - 8006:80
        
#    networks:
#      - bookstack

  bookstack_db:
    image: linuxserver/mariadb:latest
    container_name: bookstack_mariadb
    restart: unless-stopped
    volumes:
      - /mnt/Secondary/docker/bookstack/mariadb/config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_ROOT_PASSWORD=SuperPWGoesHere
      - MYSQL_PASSWORD=SuperPWGoesHere
      - MYSQL_TCP_PORT=3306      

#    networks:
#      - bookstack
#
#networks:
#  bookstack:

volumes:
  bookstack:
    name: bookstack_data
  bookstack_db:
    name: bookstack_mariadb_data      

networks:
  default:
    name: nginx-proxy-manager
    driver: bridge
    external: true
```

### Container logs

```bash
N/A
```

**Comment by aptalca** [comment]
> When the above variables are entered into "environment:" on docker-compose, it is expected that they be passed along to /config/www/.env.

That's not a valid expectation. Not sure where you read that.

The accepted env vars are listed in the readme. Apart from those, the upstream app may accept other vars, but I don't believe the app modifies the .env file to replace them with values from the environment.

**Comment by XStylus** [comment]
The following variables are passed along to /config/www/.env

      - APP_URL=https://wiki.bzstudios.com
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_PASS=KUwYXjHT7vDA4pr8
      - DB_DATABASE=bookstackapp
      - DB_PORT=3306

Is there a reason that the remaining variables are not? 

My understanding might be very flawed. I just find it bizarre that select variables are passed yet other crucial variables are not.

**Comment by XStylus** [comment]
The following variables are passed along to /config/www/.env

  - APP_URL=https://wiki.example.com
  - DB_HOST=bookstack_db
  - DB_USER=bookstack
  - DB_PASS=[REDACTED]
  - DB_DATABASE=bookstackapp
  - DB_PORT=3306
 
Is there a reason that the remaining variables are not?

My understanding might be very flawed. I just find it bizarre that select variables are passed yet other crucial variables are not.

**Comment by ssddanbrown** [comment]
@XStylus Likely because the container has custom handling for those options (options are not all the same as the env equivalents), and this somewhat aligns the DB option behaviour with many DB containers, where such env options only really apply for first boot with data persistence.

**Comment by aptalca** [comment]
The options that are required to get the app up and running are handled by the container init and are listed in the readme.

**Comment by seehma** [comment]
same issue for me, how do i set up mail sending in this bookstack-docker-image?
At first i also tried to pass them via environment-option in docker-compose file, then i tried to manually add a .env file, but neither worked -> mail sending always tries to connect to localhost...

**Comment by dac11011** [comment]
Can we get this fixed? Please don't put out another crappy, non-working Docker image (like all the others) with not enough features to even run it.  Thanks

**Comment by ssddanbrown** [comment]
Just as an additional data point, just tested this and setting mail options within `docker-compose.yml` environment works fine for me as expected.

<details><summary>My Compose File</summary>
<p>

```yml
---
version: "2"
services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack_oct_23
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=http://localhost:6875
      - DB_HOST=bookstack_db
      - DB_PORT=3306
      - DB_USER=bookstack
      - DB_PASS=mydbpass
      - DB_DATABASE=bookstackapp
      - MAIL_HOST=172.17.0.1
      - MAIL_PORT=1025
      - MAIL_USERNAME=null
      - MAIL_PASSWORD=null
      - MAIL_ENCRPYTION=null
      - MAIL_VERIFY_SSL=false
      - MAIL_FROM=test-lsio@example.com
      - MAIL_FROM_NAME="LSIO MAIL TESTING"
    volumes:
      - ./bookstack_app_data:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_oct_23_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=mydbpass
      - TZ=Europe/London
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=mydbpass
    volumes:
      - ./bookstack_db_data:/config
    restart: unless-stopped
```

</p>
</details>
