### ISSUE TITLE
Container startup does not set APP_KEY

### ISSUE THREAD

**Issue by rveachkc** [linuxserver/docker-bookstack#21]
Host: Ubuntu Server 16.04.05
No errors reported in the docker log, but the laravel.log file reported cipher errors:
```
[2019-01-25 04:23:22] production.ERROR: The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths. {"exception":"[object] (RuntimeException(code: 0): The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths. at /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:43)
```
Full log: https://pastebin.com/RjFJXfKY

Turned on APP_DEBUG, found that all DB related ENV variables were set correctly, but `APP_KEY` was still set to `SomeRandomString`, even though `/config/BOOKSTACK_APP_KEY.txt` had a valid value.
I was able to get this working by manually editing the `/config/www/.env` file with the output from `php artisan key:generate`.

I'm not configuring the container by landing a custom `/config/www/.env`, but this should probably be fixed for others.
I suspect this sed command isn't working as it should be: https://github.com/linuxserver/docker-bookstack/blob/1eaa3569b4ae5cf1436202e9c747f89978ea763d/root/etc/cont-init.d/50-config#L44

**Comment by thelamer** [comment]
You are correct, the default config file does not include the string to substitute : 
```
# Application key
# Used for encryption where needed.
# Run `php artisan key:generate` to generate a valid key.
APP_KEY=SomeRandomString

# Application URL
# Remove the hash below and set a URL if using BookStack behind
# a proxy, if using a third-party authentication option.
# This must be the root URL that you want to host BookStack on.
# All URL's in BookStack will be generated using this value.
#APP_URL=https://example.com

# Database details
DB_HOST=localhost
DB_DATABASE=database_database
DB_USERNAME=database_username
DB_PASSWORD=database_user_password

# Mail system to use
# Can be 'smtp', 'mail' or 'sendmail'
MAIL_DRIVER=smtp

# SMTP mail options
MAIL_HOST=localhost
MAIL_PORT=1025
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null


# A full list of options can be found in the '.env.example.complete' file.
```

We should also be setting the app url with an env variable, possible optional mail host options. 

https://github.com/BookStackApp/BookStack/blob/master/.env.example.complete

I will have a PR when I have a working example.

**Comment by thelamer** [comment]
We still need to update from that config file though created https://github.com/linuxserver/docker-bookstack/pull/22 .

**Comment by homerr** [comment]
Hi @rveachkc did you create the container with `DB_USER` set in the environment?

**Comment by rveachkc** [comment]
It's been a while, so I'm a bit fuzzy on the order in which I tried everything, but this was the last container definition I tried before I started configuring the .env file.  Honestly, once I got that up and running, I didn't touch it.

Partial definition in ansible yaml:

```yml

- name: Bookstack Container
  docker_container:
    name: bookstack
    image: linuxserver/bookstack
    env:
      PUID: "{{ bookstack_user_task.uid }}"
      PGID: "{{ bookstack_user_task.group }}"
      DB_HOST: "{{ mysql_container_name }}"
      DB_DATABASE: "{{ bookstack_mysql_db }}"
      DB_USERNAME: "{{ bookstack_mysql_user }}"
      DB_PASSWORD: "{{ bookstack_mysql_pw }}"
      APP_URL: "https://{{ bookstack_host }}"
      APP_KEY: "{{ bookstack_app_key }}"
      APP_DEBUG: true
```
