### ISSUE TITLE
docker compose instructions not working for first install

### ISSUE THREAD

**Issue by boulder47** [linuxserver/docker-bookstack#272]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Distributor ID:	Debian
Description:	Debian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm
Docker version 28.0.4, build b8034c0
Docker Compose version v2.34.0
docker-compose.yaml : 

```
services:
  bookstack:
    image: lscr.io/linuxserver/bookstack:latest
    container_name: bookstack
    environment:
      - PUID=2001
      - PGID=2001
      - APP_URL=http://192.168.12.231:6875
      - APP_KEY=/config/keys/cert.key
      - DB_HOST=192.169.12.231
      - DB_PORT=3306
      - DB_USERNAME=databaseuser
      - DB_PASSWORD=databasepass
      - DB_DATABASE=bookstackdb
      - REMOTE_SQL="http://192.168.12.231:3306/bookstackdb.sql"
    volumes:
      - ./bookstack_app_data:/config
    ports:
      - 6875:80
    networks:
      - bookstack_network
    restart: unless-stopped
    depends_on:
      - bookstack_db
  bookstack_db:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: bookstack_db
    environment:
      - PUID=2001
      - PGID=2001
      - MYSQL_ROOT_PASSWORD="rootpassword"
      - MYSQL_DATABASE="bookstackdb"
      - MYSQL_USER="databaseuser"
      - MYSQL_PASSWORD="databasepass"
    ports:
      - 3306:3306
    networks:
      - bookstack_network
    volumes:
      - ./bookstack_db_data:/config
    restart: unless-stopped
networks:
  bookstack_network:
    driver: bridge

```

the bookstack is waiting on the DB and nothing is happening.

### Expected Behavior

Expect it to talk to the db and start inital config / setup

### Steps To Reproduce

using a guide online for instructions as it was easier to follow.
https://omicx.cc/posts/2023-12-25-install-bookstack-by-docker/

### Environment

```markdown
- OS: debian 12
- How docker service was installed:
official instructions.
```

### CPU architecture

x86-64

### Docker creation

```bash
docker compose up -d
```

### Container logs

```bash
-----bookstack log------
Waiting for DB to be available
/etc/s6-overlay/s6-rc.d/init-bookstack-config/run: line 59:   271 Illegal instruction     (core dumped) php /app/www/artisan migrate --force
[custom-init] No custom files found, skipping...
[ls.io-init] done.
-------------------------------
------bookstack_db log----------------
[custom-init] No custom files found, skipping...
250413 17:24:01 mysqld_safe Logging to '/config/log/mysql/mariadb-error.log'.
250413 17:24:01 mysqld_safe Starting mariadbd daemon with databases from /config/databases
Connection to localhost (::1) 3306 port [tcp/mysql] succeeded!
Logrotate is enabled
[ls.io-init] done.
------------------------------------------
```
