### ISSUE TITLE
container doesn't start if DB_HOST not set in docker-compose.yml

### ISSUE THREAD

**Issue by joergr** [linuxserver/docker-bookstack#31]
Plattform: x64, Arch Linux, Docker 18.09.6-ce

When I don't provide any SQL-settings in docker-compose.yml as suggested here <https://github.com/linuxserver/docker-bookstack#advanced-users-full-control-over-the-env-file> the container doesn't come up.

```
bookstack    | [cont-init.d] 10-adduser: exited 0.
bookstack    | [cont-init.d] 20-config: executing...
bookstack    | [cont-init.d] 20-config: exited 0.
bookstack    | [cont-init.d] 30-keygen: executing...
bookstack    | using keys found in /config/keys
bookstack    | [cont-init.d] 30-keygen: exited 0.
bookstack    | [cont-init.d] 50-config: executing...
bookstack    | App Key found - setting variable for seds
bookstack    | usage: nc [-46CDdFhklNnrStUuvZz] [-I length] [-i interval] [-O length]
bookstack    | 	  [-P proxy_username] [-p source_port] [-q seconds] [-s source]
bookstack    | 	  [-T toskeyword] [-V rtable] [-w timeout] [-X proxy_protocol]
bookstack    | 	  [-x proxy_address[:port]] [destination] [port]
bookstack    | usage: nc [-46CDdFhklNnrStUuvZz] [-I length] [-i interval] [-O length]
bookstack    | 	  [-P proxy_username] [-p source_port] [-q seconds] [-s source]
bookstack    | 	  [-T toskeyword] [-V rtable] [-w timeout] [-X proxy_protocol]
bookstack    | 	  [-x proxy_address[:port]] [destination] [port]
```
and so on ... until I press control-c

The minimum environment variable I have to provide ist DB_HOST.

By the way:
Even if I set DB_HOST in docker-compose.yml the container comes up with a warning:
```
bookstack    | [cont-init.d] 50-config: executing...
bookstack    | App Key found - setting variable for seds
bookstack    | /var/run/s6/etc/cont-init.d/50-config: line 62: warning: command substitution: ignored null byte in input
bookstack    | /var/run/s6/etc/cont-init.d/50-config: line 62: warning: command substitution: ignored null byte in input
bookstack    | Nothing to migrate.
bookstack    | [cont-init.d] 50-config: exited 0.
```

Not sure, if that is an error in the container or a missleading information in the README.

docker-compose.yml
To reproduce the error I commented DB-HOST. If I uncomment the line everything runs fine.
```
version: '3'
services:
    bookstack:
        image: linuxserver/bookstack
        container_name: bookstack
        hostname: mimir
        restart: always
        environment:
            - PUID=1000
            - PGID=1000
            # - DB_HOST=mariadb
        networks:
            - web
            - dcnetwork
        expose:
            - 80
        volumes:
            - ./config:/config
        labels:
            - "traefik.enable=true"
        ...
```
And the relevant part from .env
```
APP_URL=https://mimir.xxx.xxx

# Database details
DB_HOST=mariadb
DB_DATABASE=xxx
DB_USERNAME=xxx
DB_PASSWORD=xxx
```
