### ISSUE TITLE
Unable to connect at URL

### ISSUE THREAD

**Issue by mitchellknight** [linuxserver/docker-bookstack#37]
I'm trying to run Bookstack on my dedicated CentOS server. I already have Gitea running in a Docker container so I understand _some_ Docker basics.

I want Bookstack to run at http://example.com:10081. After running `docker-compose pull` and creating a `docker-compose.yml` file (see below) and running `docker-compose up` I thought I would see Bookstack at http://example.com:10081. Instead I see "Unable to connect" in my browser. I think I'm missing something important but after reading the _readme_ file and Docs at linuxserver.io I cannot figure out what it is.

_Example docker-compose.yml_

```yaml
---
version: "2"
services:
  bookstack:
    image: linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_PASS=examplepassword
      - DB_DATABASE=bookstackapp
    volumes:
      - ./data:/config
    ports:
      - 10081:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
  bookstack_db:
    image: linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=examplepassword
      - TZ=America/New_York
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=examplepassword
    volumes:
      - ./data:/config
    restart: unless-stopped
```

Additional details: This server has WHM/cPanel, Apache, MySQL, etc. installed. I figured since Bookstack was in a Docker container that shouldn't matter. I didn't need to do anything special for Gitea (official Docker image) to work — I just had to give it a port. I was hoping Bookstack would be just as easy.

What am I missing?
