### ISSUE TITLE
 Warning: World-writable config file '/etc/mysql/conf.d/custom.cnf' is ignored...' at line 1

### ISSUE THREAD

**Issue by machond** [linuxserver/docker-bookstack#85]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

If procced with restore of database in docker similar to instruction:
`https://www.bookstackapp.com/docs/admin/backup-restore/`
you should be able to import sql file. 

## Current Behavior

If procced with restore of database in docker similar to instruction:
`https://www.bookstackapp.com/docs/admin/backup-restore/`
then you will recive error:
`ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'Warning: World-writable config file '/etc/mysql/conf.d/custom.cnf' is ignored...' at line 1
`

## Steps to Reproduce

1. Make a dump of sql: `sudo docker exec -it bookstack-db mysqldump -uroot -ppassword bookstack > bookstack.sql`
2. Try to import it: `sudo docker exec -it bookstack-db /bin/sh -c "mysql -uroot -ppassword bookstack < bookstack.sql"`
3. Error shows up

## Environment
**OS:** Docker/ Linux 5.10.0-0.bpo.3-amd64 #1 SMP Debian 5.10.13-1~bpo10+1 (2021-02-11) x86_64 GNU/Linux
**CPU architecture:** x86_64
**How docker service was installed:**

OMV 5

## Command used to create docker container (run/create/compose/screenshot)

```
version: "2"
services:

  bookstack-db:
    image: linuxserver/mariadb
    container_name: bookstack-db
    hostname: bookstack-db
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=100
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=bookstack
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=password
      
    volumes:
      - /srv/dev1212/dockerdisk/bookstack/bookstack-db-data:/config


  bookstack:
    image: linuxserver/bookstack
    container_name: bookstack
    hostname: bookstack
    restart: unless-stopped
    environment:
      - TZ=Europe/Warsaw
      - PUID=1000
      - PGID=100
      - APP_URL=https://mydomain.com
      - DB_HOST=bookstack-db
      - DB_USER=bookstack
      - DB_PASS=password
      - DB_DATABASE=bookstack



    depends_on:
      - bookstack-db
    volumes:
      - /srv/dev1212/dockerdisk/bookstack/bookstack-data:/config


```
